aws_region = "us-east-1"
vpc_name = "sola-chat-test-vpc"
vpc_cidr = "10.10.0.0/16"
IGW_name = "sola-chat-vpc-igw"
sola-chatboat-public_route_table = "sola-chat_Main_table-test"
#dynamodb_lock_name = "sola-chat-state-lock-dynamo-prod"
key_name = "iconic"
environment = "test"